services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword1234
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


volumes:
  db-data: